name: Test

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [14, 16, 18, 20]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node-version }}"

      - run: npm ci --no-audit

      - run: npx elm-json --help
